name: scan_barcode
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  path: ^1.9.0
  web_socket_channel: ^3.0.1
  image_picker: ^1.1.2
  image: ^4.5.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
